<template>
  <div>
    <div class="notification">
      <b-message type="is-info" has-icon>
        On this page you can review access to calendar sync generated by staff.
      </b-message>
      <section class="hero">
        <div class="column">
          <b-table
            :data="acl"
            narrowed
            bordered
            class="agentsListTbl"
            :loading="loading"
            paginated
          >
            <template #empty>
              <div class="has-text-centered">
                No one has created access yet.
              </div>
            </template>
            <b-table-column
              field="date_start"
              label="Agent"
              v-slot="props"
              centered
              width="140"
            >
              <b-icon
                icon="ban"
                type="is-danger"
                v-if="props.row.disabled === 1"
              ></b-icon>
              #{{ props.row.agent_id }} {{ props.row.firstname }}
              {{ props.row.lastname }}
            </b-table-column>
            <b-table-column
              field="hash"
              label="Access Hash"
              v-slot="props"
              centered
              width="140"
            >
              {{ props.row.hash }}
            </b-table-column>
            <b-table-column label="Revoke" v-slot="props" centered width="140">
              <b-button
                icon-left="ban"
                type="is-primary"
                outlined
                @click="OpenConfirmationModal(props.row.id)"
                >Revoke Access</b-button
              >
            </b-table-column>
          </b-table>
        </div>
      </section>
    </div>
  </div>
</template>

<script>
import ConfirmRevokeCalendarAccess from "../forms/ConfirmRevokeCalendarAccess.vue";

export default {
  name: "CalendarAccess",
  computed: {},
  mounted() {
    this.LoadAccessList();
  },
  methods: {
    LoadAccessList() {
      this.$http.get("./scheduleapi/calendar").then((r) => {
        if (r.data.response === "success") {
          this.acl = r.data.calendar;
        } else {
          this.$buefy.toast.open({
            message: "Error occurred. " + r.data.msg,
            type: "is-danger",
          });
        }
      });
    },
    OpenConfirmationModal(id) {
      const that = this;
      this.$buefy.modal.open({
        parent: this,
        component: ConfirmRevokeCalendarAccess,
        hasModalCard: true,
        props: { id },
        trapFocus: true,
        events: {
          reloadapi() {
            that.getRequests();
          },
        },
      });
    },
  },
  data() {
    return {
      acl: [],
      loading: false,
    };
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style >
.b-table {
  float: left;
  width: 100%;
  border: 1px solid black;
}
.b-table td {
  height: auto;
}
.b-table tr {
  height: auto !important;
}

.shiftstable thead:first-child th {
  background: rgb(165, 197, 255);
  background: linear-gradient(
    180deg,
    rgba(165, 197, 255, 1) 0%,
    rgba(40, 68, 207, 1) 100%
  );
  color: white;
}
</style>
